spring:
    application:
        name: web-service
    profiles:
      active: @spring.profiles.active@
    jackson:
        serialization.write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false

